"""Initial migration.

Revision ID: 6a5093217980
Revises: 
Create Date: 2021-01-11 16:14:47.526081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5093217980'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_info',
    sa.Column('case_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_name', sa.String(length=50), nullable=True),
    sa.Column('case_desc', sa.Text(length=100), nullable=True),
    sa.Column('case_model', sa.Enum('http', 'web', 'app'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('department',
    sa.Column('department_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('rest_case',
    sa.Column('case_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'OPTION', 'DELETE'), server_default='GET', nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('token_expire', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('auth', sa.Boolean(), nullable=True),
    sa.Column('task_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('web_case',
    sa.Column('case_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'OPTION', 'DELETE'), server_default='GET', nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('token_expire', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=True),
    sa.Column('pwd_hash', sa.String(length=128), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['department.department_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('web_case')
    op.drop_table('task')
    op.drop_table('rest_case')
    op.drop_table('department')
    op.drop_table('case_info')
    # ### end Alembic commands ###
